### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by francesco1119** [taviroquai/MapIgniter#3]
Hello I've installed MapIgniter apparently fron my output:
# root@localhost:/var/www/mapigniter# ./install.sh 
# Installing MapIgniter (install.sh)

Starting...
Unzip was found. Skipping install unzip...
Composer was found. Skipping install composer...
Installing MapIgniter...
Warning: This development build of composer is over 30 days old. It is recommended to update it by running "./composer.phar self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev)
- Installing gabordemooij/redbean (v3.4.4)
  Downloading: 100%         
- Installing jpgraph (3.5)
  Downloading: 100%         
- Installing ckeditor (3.6.4)
  Downloading: 100%         
- Installing fancybox (2.0.6)
  Downloading: 100%         
- Installing jqueryui (1.9.0)
  Downloading: 100%         
- Installing ol (2.13.1)
  Downloading: 100%         
- Installing codeigniter/framework (dev-develop 23824b8)
  Cloning 23824b85d2e51f1f7930631bd84143ff9c078b50

Writing lock file
Generating autoload files
Done! Open in the browser http://machine-ip/mapigniter/install
root@localhost:/var/www/mapigniter# 

Unfortunately when I open the address: http://localhost/mapigniter/install/ there are 2 errors:

A PHP Error was encountered

Severity: Notice

Message: Indirect modification of overloaded property CI_Input::$security has no effect

Filename: core/Input.php

Line Number: 133

Fatal error: Cannot assign by reference to overloaded object in /var/www/mapigniter/vendor/codeigniter/framework/system/core/Input.php on line 133
A PHP Error was encountered

Severity: Error

Message: Cannot assign by reference to overloaded object

Filename: core/Input.php

Line Number: 133

**Comment by taviroquai** [comment]
The errors above have origin in CodeIgniter framework and have been fixed.
